# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRPqGxv8-ZSek_muiDbZXhQuGFfGAEIW
"""

from google.colab import files

print("الرجاء اختيار ملف الفيديو الذي تريد تتبع جسم فيه...")
uploaded = files.upload()

# حفظ اسم الفيديو الذي تم رفعه
video_filename = list(uploaded.keys())[0]
print(f"تم رفع الفيديو: {video_filename}") #https://www.youtube.com/watch?v=T_PYhcHp0JE

import cv2
import numpy as np

# --- 1. الإعدادات الأساسية ---

# اسم الفيديو الذي رفعته في الخطوة السابقة
input_video_path = video_filename

# اسم الفيديو الناتج الذي سيتم حفظه
output_video_path = 'output_tracking_video.mp4'

# --- 2. تعريف نطاق اللون (باستخدام HSV) ---
# هذا المثال جاهز لتتبع اللون "الأزرق"
# يمكنك تغيير هذه القيم لتتبع أي لون آخر
# H (اللون): 0-179
# S (التشبع): 0-255
# V (السطوع): 0-255
lower_color = np.array([100, 150, 50])  # الحد الأدنى للون الأزرق
upper_color = np.array([140, 255, 255]) # الحد الأعلى للون الأزرق

# (اختياري) مثال للون الأخضر:
# lower_color = np.array([40, 70, 70])
# upper_color = np.array([80, 255, 255])

# (اختياري) مثال للون الأحمر:
# lower_color = np.array([160, 150, 50])
# upper_color = np.array([180, 255, 255])


# --- 3. معالجة الفيديو ---

print(f"بدء معالجة الفيديو: {input_video_path}")

# فتح ملف الفيديو للقراءة
cap = cv2.VideoCapture(input_video_path)

# التأكد من أن الفيديو فتح بنجاح
if not cap.isOpened():
    print(f"خطأ: لم يتمكن من فتح ملف الفيديو {input_video_path}")
else:
    # جلب معلومات الفيديو الأصلية لحفظ الفيديو الجديد بنفس المواصفات
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    # إعداد كائن "كاتب الفيديو" لحفظ النتيجة
    fourcc = cv2.VideoWriter_fourcc(*'mp4v') # Codec لحفظ الفيديو
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (frame_width, frame_height))

    print("جاري معالجة الإطارات... قد يستغرق هذا بعض الوقت.")

    # حلقة (Loop) لقراءة كل إطار (frame) في الفيديو
    while True:
        # قراءة إطار واحد
        ret, frame = cap.read()

        # إذا (ret) كانت False، فهذا يعني أن الفيديو انتهى
        if not ret:
            break

        # 1. تحويل الإطار من نظام ألوان BGR إلى HSV
        # (نظام HSV أسهل للتعرف على الألوان من BGR)
        hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

        # 2. إنشاء "ماسك" (قناع) يعزل اللون الذي نريده فقط
        # أي بكسل يقع لونه بين lower_color و upper_color سيصبح "أبيض"
        # والباقي سيصبح "أسود"
        mask = cv2.inRange(hsv_frame, lower_color, upper_color)

        # (اختياري) تحسين الماسك لإزالة التشويش
        mask = cv2.erode(mask, None, iterations=2)
        mask = cv2.dilate(mask, None, iterations=2)

        # 3. إيجاد الكونتور (الخطوط الخارجية) للأجسام في الماسك
        contours, _ = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # متغير لتتبع أكبر جسم تم العثور عليه (لتجنب تتبع النقاط الصغيرة)
        best_contour = None
        best_area = 0

        for contour in contours:
            area = cv2.contourArea(contour)
            # نبحث عن أكبر جسم مساحته أكبر من 500 بكسل (لتجاهل التشويش)
            if area > 500 and area > best_area:
                best_area = area
                best_contour = contour

        # 4. إذا وجدنا جسماً، نرسم مستطيل حوله
        if best_contour is not None:
            # حساب إحداثيات المستطيل المحيط بالجسم
            (x, y, w, h) = cv2.boundingRect(best_contour)

            # رسم المستطيل على الإطار الأصلي (باللون الأخضر)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            # كتابة "Object" فوق المستطيل
            cv2.putText(frame, 'Object Detected', (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        # 5. كتابة الإطار (سواء تم التعديل عليه أم لا) في ملف الفيديو الجديد
        out.write(frame)

    # بعد انتهاء الحلقة، أغلق ملفات الفيديو
    cap.release()
    out.release()
    cv2.destroyAllWindows()

    print(f"اكتملت المعالجة! تم حفظ الفيديو باسم: {output_video_path}")